spring:
  output.ansi.enabled: always
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  application.name: spring-batch-job
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:./target/hsqldb/${spring.application.name};ifexists=false;hsqldb.lock_file=false
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  batch:
    job:
      enabled: false
spring-batch-job:
  scheduled-cron-expression: "0 */1 * * * ?"
  path-to-import-file: "src/main/resources/filesToImport"

import:
  strategy:
    csv:
      type: file
      extension: csv
      datasource: src/main/resources/filesToImport
    txt:
      type: file
      extension: txt
      datasource: src/main/resources/filesToImport